import "./globals.css";
import { Cormorant_Garamond, DM_Sans } from "next/font/google";

const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cormorantGaramond",
});
const dMSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dMSans",
});

export const metadata = {
  title: "Tellis Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dMSans.variable} ${cormorantGaramond.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}

